### ISSUE TITLE
2018 Survey Data Scrub

### ISSUE THREAD

**Issue by Foggalong** [unixporn/surveys#2]
Data for the following questions needs scrubbing before release:

* [x] Demographics
  * [x] Gender
  * [x] Age
  * [x] Country
  * [x] Job
* [x] Meta
  * [x] Subreddit Activity
  * [x] Previous Survey Completion
  * [x] Modding
  * [x] Details
  * [x] Defaults
  * [x] Hosts
  * [x] Limits
  * [x] Curation
  * [x] Discord
  * [x] Rating
* [ ] Linux
  * [x] Usage 
  * [x] Distro
  * [ ] Why Distro
  * [x] DE/WM
  * [ ] Why DE/WM
  * [x] GTK
  * [ ] Icon 
  * [ ] Monospace Font
  * [ ] Proportional Font
  * [x] Sysinfo
  * [ ] Browser
  * [ ] Editor
  * [x] Terminal
  * [ ] Shell
  * [ ] Hardware
  * [ ] Wayland
* [ ] macOS
  * [x] Usage
  * [ ] Why macOS
  * [ ] Env
  * [x] Homebrew
  * [ ] Shell
  * [ ] Browser
  * [ ] Editor
  * [ ] Hardware
* [ ] BSD
  * [x] Usage 
  * [ ] Variant
  * [ ] Why Variant
  * [ ] DE/WM
  * [ ] Why DE/WM
  * [ ] GTK
  * [ ] Icon 
  * [ ] Monospace Font
  * [ ] Proportional Font
  * [ ] Sysinfo
  * [ ] Browser
  * [ ] Editor
  * [ ] Terminal
  * [ ] Shell
  * [ ] Hardware
  * [ ] Wayland
* [ ] Windows
  * [x] Usage
  * [ ] Version
  * [ ] Why Windows
  * [x] WSL/Cygwin
  * [ ] Browser
  * [ ] Editor
  * [ ] Hardware
* [ ] Mobile
  * [x] Usage
  * [ ] OS
  * [x] JB/Root
  * [ ] ROM
  * [ ] Why OS?
  * [ ] Virtualise
* [ ] Other OS
  * [ ] Usage
  * [ ] Hardware

**Comment by 9viz** [comment]
I'm doing GTK, terminal and sysinfo.

**Comment by izPanda** [comment]
I'm working on Browser, Editor, Shell, Hardware, and Wayland today
